// Per-track copyright statement PDF. Uses Noto Sans KR (bundled in
// server/assets/) so Korean titles, prompts, and user names render correctly.
// pdfkit's built-in fonts can't draw Hangul.
//
// The body avoids "fi" letter combinations because Noto Sans KR's GSUB
// emits a single 'fi' glyph whose ToUnicode mapping pdfkit doesn't
// decompose — so text extraction returns "Certifcate" / "fle". Visual
// is fine; the extraction matters for screen readers and copy-paste.
import PDFDocument from "pdfkit";
import { dirname, join } from "path";
import { fileURLToPath } from "url";
import type { AuthUser } from "./auth.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const KO_FONT = join(__dirname, "assets", "NotoSansKR-Regular.otf");

const TIER_LABEL: Record<string, string> = {
  free: "Free",
  starter: "Starter",
  pro: "Pro",
};

export interface CertSong {
  id: string;
  title: string;
  prompt: string;
  audioUrl: string | null;
  createdAt: Date;
}

export function renderCert(user: AuthUser, song: CertSong): NodeJS.ReadableStream {
  const watermarked = !!song.audioUrl?.endsWith("-wm.mp3");
  const doc = new PDFDocument({ size: "A4", margin: 56 });
  doc.registerFont("Body", KO_FONT);
  doc.font("Body");

  doc.fontSize(28).fillColor("#111").text("MOUSIKE");
  doc.moveDown(0.2);
  doc.fontSize(12).fillColor("#666").text("AI Music — Audio License Statement");

  section(doc, "Track");
  drawRow(doc, "Title", song.title);
  drawRow(doc, "Track ID", song.id);
  drawRow(doc, "Prompt", song.prompt);
  drawRow(doc, "Generated", song.createdAt.toISOString());

  section(doc, "Issued to");
  drawRow(doc, "User", user.name ?? user.email);
  drawRow(doc, "Email", user.email);
  drawRow(doc, "Plan", TIER_LABEL[user.tier] ?? user.tier);

  section(doc, "License");
  doc.fontSize(11).fillColor("#222").text(
    "This track was generated by Mousike using the ACE-Step 1.5 model " +
      "(Apache License 2.0). The user named above holds a royalty-free, " +
      "perpetual, worldwide right to use, distribute, and monetize the " +
      "resulting audio in commercial works, including but not limited to " +
      "video, advertising, streaming, podcasts, and games.",
    { align: "left", lineGap: 2 },
  );
  if (watermarked) {
    doc.moveDown(0.6);
    doc.fontSize(10).fillColor("#a44").text(
      "Note: this audio track includes an audible \"Mousike\" voice tag at the " +
        "start and end (Free plan). Upgrade to remove.",
      { align: "left", lineGap: 2 },
    );
  }

  doc.moveDown(1.5);
  doc.fontSize(9).fillColor("#888").text(
    `Issued by Mousike on ${new Date().toISOString().slice(0, 10)}. ` +
      `This document records the user's license under Mousike's terms; ` +
      `it is not a substitute for independent legal advice.`,
    { align: "left", lineGap: 1 },
  );

  doc.end();
  return doc;
}

function section(doc: PDFKit.PDFDocument, title: string) {
  doc.moveDown(1.2);
  doc.x = doc.page.margins.left;
  doc.fontSize(16).fillColor("#111").text(title);
  doc.moveDown(0.4);
}

// Two-column row: bold label on the left, value on the right. Both share the
// same Y so they line up; we advance Y by the taller of the two so multi-line
// values don't get overwritten by the next row.
function drawRow(doc: PDFKit.PDFDocument, label: string, value: string) {
  const x0 = doc.page.margins.left;
  const labelWidth = 90;
  const gap = 12;
  const valueX = x0 + labelWidth + gap;
  const valueWidth = doc.page.width - valueX - doc.page.margins.right;
  const y = doc.y;

  doc.fontSize(11).fillColor("#666").text(label, x0, y, { width: labelWidth });
  doc.fontSize(11).fillColor("#111").text(value, valueX, y, { width: valueWidth });

  const labelHeight = doc.heightOfString(label, { width: labelWidth });
  const valueHeight = doc.heightOfString(value, { width: valueWidth });
  doc.y = y + Math.max(labelHeight, valueHeight) + 4;
}
